apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rozklad
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: registry.scalamandra.com/ais-rs/ais-rs-backend:latest
          name: backend
          env:
            REDIS_HOST: redis-master
          ports:
            - containerPort: 5000
              name: http
            - containerPort: 5001
              name: raw
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 1100m
              memory: 1000Mi

      imagePullSecrets:
        - name: githubRozkladRegistrySecret
