apiVersion: v1
kind: Service
metadata:
  namespace: rozklad
  labels:
    app: backend
  name: backend
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
    - port: 81
      targetPort: 5001
      protocol: TCP
      name: raw
  selector:
    app: backend
