version: '3.3'
services:
  backend:
    image: rozklad-backend
    restart: always
    container_name: rozklad-backend
    environment:
      REDIS_HOST: redis
    ports:
      - '5005:5001'

  redis:
    image: redis
    restart: always
    container_name: rozklad-redis